openapi: 3.0.0
info:
  title: Admin Panel API
  description: API documentation for Admin Panel API
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000
    description: local server

# Authentication
paths:
  /auth:
    post:
      tags:
        - Authentication
      description: Generate JWT token to access forbidden content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: example@gmail.com
              password: ''
      responses:
        '201':
          description: JWT token generated successfully.
        '404':
          description: Credentials are incorrect.

  # Company
  /all-company:
    get:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Fetch list of all company
      responses:
        '200':
          description: Companies's list successfully fetched.
        '404':
          description: Companies's list not found.

  /add-company:
    post:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Add one company to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                logoUrl:
                  type: string
                establishmentDate:
                  type: string
            example:
              name: Google
              website: https://google.com
              logoUrl: https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
              establishmentDate: '1998-09-04'
      responses:
        '201':
          description: Company saved successfully.
        '400':
          description: Company already exists.
        '404':
          description: Company save failed.

  /get-one-company:
    post:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Fetch details about one company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: ''
      responses:
        '200':
          description: Company details successfully fetched.
        '404':
          description: Company not found.

  /change-company:
    put:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Change details of certain company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                logoUrl:
                  type: string
                establishmentDate:
                  type: string
                id:
                  type: string
            example:
              id: ''
              name: Company Name
              website: https://comany.com
              logoUrl: https://comany.com/wp-content/uploads/2022/01/companyLogo.svg
              establishmentDate: '2014-01-01'
      responses:
        '201':
          description: Company details changed successfully.
        '404':
          description: Not found.

  /delete-company:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Delete one company from the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: ''
      responses:
        '200':
          description: Company deleted successfully.
        '404':
          description: Company not found to delete.

  # Employee

  /all-employee:
    get:
      security:
        - bearerAuth: []
      tags:
        - Employee
      description: Fetch list of all employee
      responses:
        '200':
          description: Employees's list successfully fetched.
        '404':
          description: Employees's list not found.

  /add-employee:
    post:
      security:
        - bearerAuth: []
      tags:
        - Employee
      description: Add employee to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                startedAt:
                  type: string
                birthDate:
                  type: string
                personalNumber:
                  type: string
                position:
                  type: string
                id:
                  type: string
            example:
              firstName: Saba
              lastName: Vartasashvili
              startedAt: '2022-03-11'
              birthDate: '2002-01-08'
              personalNumber: '12345678910'
              position: Web developer
              id: ''
      responses:
        '201':
          description: Employee saved successfully.
        '400':
          description: Employee with the same personal number already exists.
        '404':
          description: Company not found.

  /get-one-employee:
    post:
      security:
        - bearerAuth: []
      tags:
        - Employee
      description: Fetch details about one employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: ''
      responses:
        '200':
          description: Employee details successfully fetched.
        '404':
          description: Employee not found.

  /change-employee:
    put:
      security:
        - bearerAuth: []
      tags:
        - Employee
      description: Change details of certain employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                personalNumber:
                  type: string
                startedAt:
                  type: string
                birthDate:
                  type: string
                position:
                  type: string
                id:
                  type: string
                worksInCompanyId:
                  type: string
            example:
              firstName: Employee
              lastName: superEmployee
              personalNumber: '12345678910'
              startedAt: '2022-01-25'
              birthDate: '2000-09-12'
              position: 'Full stack developer'
              id: ''
              worksInCompanyId: ''
      responses:
        '201':
          description: Employee details changed successfully.
        '404':
          description: Not found.

  /delete-employee:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Employee
      description: Delete one Employee from the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: ''
      responses:
        '200':
          description: Employee deleted successfully.
        '404':
          description: Not found.
