openapi: 3.0.0
info:
  title: Admin Panel API
  description: API documentation for Admin Panel API
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000
    description: local server
  - url: http://producation.app
    description: production server

# Authentication
paths:
  /auth:
    post:
      tags:
        - Authentication
      description: Generate JWT token to access forbidden content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: sabavar@redberry.ge
              password: saba
      responses:
        '201':
          description: JWT token generated successfully.
        '404':
          description: Credentials are incorrect.

  # Company
  /all-company:
    get:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Fetch list of all company
      responses:
        '200':
          description: Companies's list successfully fetched.
        '404':
          description: Companies's list not found.

  /add-company:
    post:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Add one company to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                logoUrl:
                  type: string
                establishmentDate:
                  type: string
            example:
              name: Redberry
              website: https://redberry.international/
              logoUrl: https://redberry.international/wp-content/uploads/2022/01/redberrylogo.svg
              establishmentDate: '2014-01-01'
      responses:
        '201':
          description: Company saved successfully.
        '400':
          description: Company already exists.
        '404':
          description: Company save failed.

  /one-company:
    post:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Fetch details about one company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: 62a5ae7308540d6d70b0820b
      responses:
        '200':
          description: Company details successfully fetched.
        '404':
          description: Company not found.

  /change-company:
    put:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Change details of certain company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                logoUrl:
                  type: string
                establishmentDate:
                  type: string
                id:
                  type: string
            example:
              name: Redberry
              website: https://redberry.international/
              logoUrl: https://redberry.international/wp-content/uploads/2022/01/redberrylogo.svg
              establishmentDate: '2014-01-01'
              id: 62a5ae7308540d6d70b0820b
      responses:
        '201':
          description: Company details changed successfully.
        '400':
          description: Company with requested name already exists.
        '404':
          description: Company does not exist/not found.

  /delete-company:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Company
      description: Delete one company from the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            example:
              id: 62a5ae7308540d6d70b0820b
      responses:
        '200':
          description: Company deleted successfully.
        '404':
          description: Company not found to delete.

  # Employee
  /add-employee:
    post:
      security:
        - bearerAuth: []
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                startedAt:
                  type: string
                birthDate:
                  type: string
                personalNumber:
                  type: string
                position:
                  type: string
                id:
                  type: string
            example:
              firstName: Saba
              lastName: Vartasashvili
              startedAt: '2016-01-01'
              birthDate: '2002-01-01'
              personalNumber: '12345678910'
              position: Xaker
              id: 62a37de8c9bc3021399cad31
      responses:
        '201':
          description: Employee saved successfully.
        '404':
          description: Company not found.
